###
# @name getPlan
GET http://localhost:3000/api/trainingsplan/auth0|691343d8c21036492a17e01e
Accept: application/json

###
@taskId = {{getPlan.response.body.$[0].tasks.[0]._id}}

###
# @name getUser
GET http://localhost:3000/api/user/auth0|691343d8c21036492a17e01e
Accept: application/json

###
@userAuth0ID = {{getUser.response.body.auth0ID}}

###
POST http://localhost:3000/api/completedTasks/auth0|691343d8c21036492a17e01e
Content-Type: application/json

{
    "id": "{{taskId}}"
}

###

GET http://localhost:3000/api/completedTasks/auth0|691343d8c21036492a17e01e
