
POST http://localhost:3000/api/user/juliusdittrich2@gmail.com

### 

POST http://localhost:3000/api/trainingsplan/juliusdittrich22@gmail.com
Content-Type: application/json

{
    "name": "mein trainingsplan",
    "tasks": [
        {
            "title": "erste task",
            "description": "nur zum testen",
            "difficulty": "easy",
            "day": "Mon"
        }
    ]
}

###

GET http://localhost:3000/api/trainingsplan/juliusdittrich22@gmail.com