###

GET http://localhost:3000

###
POST http://localhost:3000/api/tasks
Content-Type: application/json

{
    "user_id": "juliusdittrich",
    "day": "Monday",
    "name": "Kniebeugen"
}

###
GET http://localhost:3000/api/tasks/juliusdittrich

###

POST http://localhost:3000/api/users
Content-Type: application/json

{
    "email": "juliusdittrich22@gmail.com"
}
